version: "3.9"
services:
  mysql5.7:
    image: mysql:5.7.31
    restart: always
    container_name: mysql5.7
    ports:
      - 3306:3306
    volumes: 
       - ./mysql/conf:/etc/mysql/conf.d
       - ./mysql/data/:/var/lib/mysql
       - ./nacos/nacos-mysql.sql:/docker-entrypoint-initdb.d/nacos-mysql.sql
       - ./xxl-job/tables_xxl_job.sql:/docker-entrypoint-initdb.d/tables_xxl_job.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --lower_case_table_names=1
    networks:
      - safety-net

  nacos:
    image: nacos/nacos-server:v2.0.4
    container_name: nacos
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    env_file:
      - ./nacos/nacos-standlone-mysql.env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql5.7
    restart: always
    networks:
      - safety-net

  zookeeper:
    image: zookeeper:3.5.9
    restart: always
    container_name: zookeeper
    volumes:
      - ./zookeeper/config:/conf
      - ./zookeeper/data:/data
      - ./zookeeper/logs:/datalog
    ports: 
      - "2181:2181"
    networks:
      - safety-net
  
  kafka:
    image: wurstmeister/kafka:2.13-2.7.2
    restart: always
    container_name: kafka
    depends_on:
        - zookeeper
    ports:
        - 9092:9092
    environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: PLAINTEXT://:9092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
        KAFKA_BROKER_ID: 1
    networks:
      - safety-net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - safety-net
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/data:/data:rw
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf "

  xxl-job:
    image: xuxueli/xxl-job-admin:2.1.2
    restart: always
    hostname: admin
    container_name: xxl-job
    ports:
      - 9880:8080
    volumes:
      - "./xxl-job/data/applogs:/data/applogs"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql5.7:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - spring.datasource.password=secret
    depends_on: 
      - mysql5.7
    networks:
      - safety-net
networks:
  safety-net:
    driver: bridge



